### ISSUE TITLE
The feed_version in feed_info.txt is not being updated

### ISSUE THREAD

**Issue by kona314** [whatcomtrans/publicwtadata#2]
I've noticed that the version of the feed, contained in the `feed_version` column of `feed_info.txt`, is not being updated after some new datasets are released. For instance, the [most recent commit](https://github.com/whatcomtrans/publicwtadata/commit/4db051bb4a7518d498372044de3f65c95036e6b9) comes just a few days after the previous one, the trip IDs in `trips.txt` have completely changed, as well as the calendar and other files. I've noticed it a handful of other times too.

This causes a particular problem for my system, which relies on this field to monitor updates.

**Comment by joshn-ridewta-com** [comment]
Thanks for pointing that out, we will investigate.  We switched to new software for generating the GTFS, this may be a bug in that process.

**Comment by danielm-ridewta** [comment]
@kona314, this should be resolved now. Sorry for the inconvenience and thanks again for letting us know.
