### ISSUE TITLE
Trip IDs in realtime feeds not present in static feed

### ISSUE THREAD

**Issue by kona314** [whatcomtrans/publicwtadata#3]
Hi all, 

After the latest GTFS update (with new version number, thanks!), I've noticed that some vehicles in the GTFS-rt feeds are reporting trip IDs that don't exist in the static feeds. 

For instance, coach 894 was reporting on trip `1120020`. This `trip_id` does not appear in `trips.txt`. 

Possibly related: Trip IDs `1120020_merged_1797627` and `1120020_merged_1798242` both exist, and they each have an extra field called `original_trip_id` with a value of `1120020`. If it helps, based on the `route_id` in GTFS-rt, this coach was actually serving `1120020_merged_1797627` (supported by the fact that it later appeared on the next trip in that block).

**Comment by danielm-ridewta** [comment]
Hi @kona314,

The merged `trip_ids` (`xxxxxxx_merged_xxxxxxx`) are created when we merge two feeds together. This is typically done 1-2 weeks before a new service schedule is published and allows us to send the feed to Google for processing before the new schedule goes into effect. This ensures that there is not a lapse GTFS feed coverage when the new schedule is published due to processing issues.
 
If your code relies on the GTFS-RT `trip_id` field to match a `trip_id` in `trips.txt`, you may have to reference `original_trip_id` for the merged cases.

**Comment by stillinbeta** [comment]
Is there another merge process going? I don't see any `original_trip_id` right now, but none of the ids in the realtime feed are showing up in trips.txt:

```
no such trip 1154090
no such trip 613090
no such trip 123090
no such trip 34090
no such trip 1088090
no such trip 1907090
no such trip 349090
no such trip 1698090
no such trip 1534090
no such trip 2027090
no such trip 790090
no such trip 224090
no such trip 742090
```

etc

**Comment by danielm-ridewta** [comment]
Sorry about that. There was an issue with the static feed matching up with the realtime feed on our end. I've pushed a new static feed that should match up better now.

**Comment by kona314** [comment]
Looks like the new service change is in effect, but the merged dataset is still current, which is creating this same problem. Can we expect an unmerged version soon?

**Comment by andymwta** [comment]
The unmerged schedule has now been posted.

**Comment by kona314** [comment]
Hi all, 

This has become a problem again. There is no merged feed posted, so it's not quite the same issue. It looks like there simply just wasn't an updated GTFS posted. 

As an example, as I write this, vehicle 829 is reporting on trip ID 730020, a 540. This trip does not exist in the feed.

**Comment by andymwta** [comment]
Apologies for the issues.
There's a new merged dataset now published that should resolve the issue.
Just as a heads up, the unmerged dataset will go live on the 18th.
